yarnPath: .yarn/releases/yarn-berry.js

pnpFallbackMode: none

packageExtensions:
  '@angular-devkit/build-angular@*':
    peerDependencies:
      '@angular/core': '*'
      karma: '*'
      protractor: '*'
    peerDependenciesMeta:
      karma: {optional: true}
      protractor: {optional: true}
  '@ngtools/webpack@*':
    peerDependencies:
      '@angular/core': '*'
  webpack@*:
    dependencies:
      events: '^3.0.0'

  # '@angular/core@*':
  #   peerDependenciesMeta:
  #     '@angular/compiler': {optional: true}
